services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_CONVEX_URL=${VITE_CONVEX_URL}
      - CONVEX_SITE_URL=${CONVEX_SITE_URL}
    restart: unless-stopped
    networks:
      - fitness-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for HTTPS
  # You can uncomment this if you need SSL termination
  # nginx-proxy:
  #   image: nginxproxy/nginx-proxy:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - certs:/etc/nginx/certs
  #     - vhost:/etc/nginx/vhost.d
  #     - html:/usr/share/nginx/html
  #   restart: unless-stopped
  #   networks:
  #     - fitness-network

networks:
  fitness-network:
    driver: bridge

# Optional volumes for SSL certificates
# volumes:
#   certs:
#   vhost:
#   html: 