services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT:-3000}:80"
      - "${HTTPS_PORT:-3443}:443"
    environment:
      - VITE_CONVEX_URL=${VITE_CONVEX_URL}
      - CONVEX_SITE_URL=${CONVEX_SITE_URL}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - fitness-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  fitness-network:
    driver: bridge 